import type { Permission } from '@/modules/auth/auth.types'

export const permissions = {
  userRead: 'user:read',
  userCreate: 'user:create',
  userUpdate: 'user:update',
  userDisable: 'user:disable',
  roleRead: 'role:read',
  roleManage: 'role:manage',
  paperRead: 'paper:read',
  paperImport: 'paper:import',
  paperDelete: 'paper:delete',
  contactReadMasked: 'contact:read_masked',
  contactReadFull: 'contact:read_full',
  contactVerify: 'contact:verify',
  contactExport: 'contact:export',
  jobManage: 'job:manage',
  templateRead: 'template:read',
  templateManage: 'template:manage',
  smtpRead: 'smtp:read',
  smtpManage: 'smtp:manage',
  campaignRead: 'campaign:read',
  campaignCreate: 'campaign:create',
  campaignApprove: 'campaign:approve',
  campaignSend: 'campaign:send',
  campaignPause: 'campaign:pause',
  analyticsRead: 'analytics:read',
  auditRead: 'audit:read',
  systemManage: 'system:manage',
} as const satisfies Record<string, Permission>
